coordinate_mode: star
relationships: []
llm: "gpt-4o-mini"

environment:
  type: DB
  name: "DB Simulation Environment"
  max_iterations: 5
  init_sql: |
    CREATE TABLE accounts (
      account_id SERIAL PRIMARY KEY,
      account_number VARCHAR(50) UNIQUE NOT NULL,
      account_type VARCHAR(50) NOT NULL,
      customer_id INTEGER,
      balance DECIMAL(15,2) NOT NULL,
      last_transaction_date TIMESTAMP
    );
    
    CREATE TABLE transactions (
      transaction_id SERIAL PRIMARY KEY,
      account_id INTEGER REFERENCES accounts(account_id),
      transaction_type VARCHAR(50) NOT NULL,
      amount DECIMAL(15,2) NOT NULL,
      timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      status VARCHAR(50) NOT NULL
    );
    
    CREATE TABLE stock_trades (
      trade_id SERIAL PRIMARY KEY,
      account_id INTEGER REFERENCES accounts(account_id),
      stock_symbol VARCHAR(10) NOT NULL,
      quantity INTEGER NOT NULL,
      price_per_share DECIMAL(10,2) NOT NULL,
      total_value DECIMAL(15,2) NOT NULL,
      trade_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    CREATE TABLE compliance_logs (
      log_id SERIAL PRIMARY KEY,
      transaction_id INTEGER,
      compliance_check VARCHAR(100) NOT NULL,
      result VARCHAR(50) NOT NULL,
      timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO accounts (account_number, account_type, balance) VALUES
    ('ACC001', 'Checking', 50000.00),
    ('ACC002', 'Savings', 100000.00),
    ('ACC003', 'Investment', 250000.00),
    ('ACC004', 'Trading', 75000.00),
    ('ACC005', 'Money Market', 200000.00);
    INSERT INTO transactions (account_id, transaction_type, amount, status) VALUES
    (1, 'Deposit', 1000.00, 'Completed'),
    (1, 'Withdrawal', 500.00, 'Completed'),
    (2, 'Deposit', 2000.00, 'Completed'),
    (3, 'Deposit', 1500.00, 'Completed'),
    (3, 'Withdrawal', 300.00, 'Completed'),
    (4, 'Deposit', 5000.00, 'Completed'),
    (5, 'Deposit', 10000.00, 'Completed');

    INSERT INTO stock_trades (account_id, stock_symbol, quantity, price_per_share, total_value) VALUES
    (1, 'AAPL', 10, 150.00, 1500.00),
    (2, 'GOOGL', 5, 1000.00, 5000.00),
    (3, 'AMZN', 2, 2000.00, 4000.00),
    (4, 'MSFT', 8, 250.00, 2000.00),
    (5, 'TSLA', 3, 700.00, 2100.00);

    INSERT INTO compliance_logs (transaction_id, compliance_check, result) VALUES
    (1, 'Anti-Money Laundering', 'Passed'),
    (2, 'Anti-Money Laundering', 'Passed'),
    (3, 'Anti-Money Laundering', 'Passed'),
    (4, 'Anti-Money Laundering', 'Passed'),
    (5, 'Anti-Money Laundering', 'Passed'),
    (6, 'Anti-Money Laundering', 'Passed'),
    (7, 'Anti-Money Laundering', 'Passed');

  anomalies:  
    - anomaly: VACUUM
      threads: 100
      ncolumn: 20
      nrow:    20000
      colsize: 100

communication: False

task:
  content: |
    The sysbench database manages complex transaction records, stock trades, and compliance tracking. Recently, during peak trading hours, the database monitoring system triggered an alert. 
    Recently, during operation, the database monitoring system has triggered an alert. Analyze the database alerts & outputs and find out the reason that caused it. The root cause can be only one of the following: 'Sync Commits', 'Many Inserts', 'High Updates', 'Many Deletes', 'Index Missing', 'Redundant Indexes', 'Large Data Insert', 'Large Data Fetch', 'Poor Join Performance', 'Correlated Subquery'. The planner should ask different experts to work on the same task, and summarize their opinions into a final prediction. Please make the decision after using all these tools, as a premature decision may lead to incorrect conclusions.

  output_format: |
    Please make the decision after using all these tools, as a premature decision may lead to incorrect conclusions.
    Please choose the most likely cause of the database anomaly from the following list, based on the expert agents: 
    'INSERT_LARGE_DATA', 'VACUUM', 'LOCK_CONTENTION', 'VACUUM', 'REDUNDANT_INDEX', 'INSERT_LARGE_DATA,IO_CONTENTION', 'FETCH_LARGE_DATA,CORRELATED_SUBQUERY', 'POOR_JOIN_PERFORMANCE,CPU_CONTENTION'
    You can ONLY CHOOSE THREE.
    Please make the decision after using all these tools, as a premature decision may lead to incorrect conclusions.
    These functions include:

    get_alerts_handler:
      Retrieves and formats current alerts from Prometheus, returning detailed information about each alert, including name, severity, description, state, active since, and value.

    detect_metric_abnormality_handler:
      Checks for anomalies in a specified metric using data from the last 10 minutes. It maps the metric name, retrieves the data, and uses a statistical method to identify abnormalities.

    get_alert_metrics_handler:
      Retrieves metrics related to current alerts and returns a detailed explanation of the alert metrics.

    get_rag_handler:
      Retrieves relevant knowledge from the Retrieval-Augmented Generation (RAG) system based on the expert and metric name, and returns an explanation.

    get_slow_query_handler:
      Retrieves information about the slowest queries executed in the database and returns an explanation. output_format: |

  labels: 
    - 'INSERT_LARGE_DATA'
    - 'VACUUM'
    - 'LOCK_CONTENTION'
    - 'VACUUM'
    - 'REDUNDANT_INDEX'
    - 'INSERT_LARGE_DATA,IO_CONTENTION'
    - 'FETCH_LARGE_DATA,CORRELATED_SUBQUERY'
    - 'POOR_JOIN_PERFORMANCE,CPU_CONTENTION'
  root_causes: 
    - 'VACUUM'
  number_of_labels_pred: 3

agents:
  - type: BaseAgent
    agent_id: agent1
    profile: "agent1 is a ConfigurationExpert that specializes in system configurations and optimizations."
  - type: BaseAgent
    agent_id: agent2
    profile: "agent2 is a CpuExpert that specializes in CPU architecture, performance, and optimizations."
  - type: BaseAgent
    agent_id: agent3
    profile: "agent3 is a WorkloadExpert that specializes in analyzing workloads, resource allocation, and optimization for efficiency."
  - type: BaseAgent
    agent_id: agent4
    profile: "agent4 is a DiskExpert that specializes in disk I/O, storage, and optimization for performance."
  - type: BaseAgent
    agent_id: agent5
    profile: "agent5 is a QueryExpert that specializes in query optimization, indexing, and performance tuning."

memory:
  type: SharedMemory

metrics: 
  accuracy: true
  response_time: true

output:
  file_path: "result/FINANCIAL_VACUUM_RESULT.json"

engine_planner:
  initial_progress: "Starting the simulation."