agents:
- agent_id: agent1
  profile: 'I am a researcher dedicated to exploring the intersection of human-computer
    interaction, brain-computer interfaces (BCIs), and machine learning. My recent
    work has focused on enhancing human performance through innovative training methods,
    such as developing a haptic feedback system to train individuals in executing
    complex bimanual polyrhythms. This project demonstrated that participants could
    significantly improve their coordination in under five minutes of adaptive training.


    In another project, I combined cutting-edge BCI technology with ultrasonic sensors
    to create a hands-free wheelchair capable of navigating crowded environments.
    This system not only allows users to control the wheelchair with their thoughts
    but also incorporates safety features for obstacle avoidance. Testing with human
    subjects showed promising results, with participants successfully controlling
    the wheelchair''s destination after minimal training.


    Additionally, I have developed a self-supervised perceptual prediction framework
    for temporal event segmentation in long videos, which is particularly relevant
    for analyzing extensive datasets, such as wildlife monitoring footage. This approach
    leverages deep learning techniques to build stable representations of objects
    over time, achieving impressive recall rates without the need for labeled data.


    My work aims to push the boundaries of how we interact with technology, making
    it more intuitive and accessible while addressing real-world challenges. I am
    committed to sharing my findings and datasets with the research community to foster
    collaboration and innovation in these fields.'
  type: BaseAgent
- agent_id: agent2
  profile: 'I am a researcher specializing in computer vision and deep learning, with
    a focus on developing innovative solutions for complex visual recognition tasks.
    My recent work has centered on estimating 3D human poses from single RGB images,
    where I demonstrated that incorporating camera viewpoints significantly enhances
    accuracy without relying on traditional geometric models. I have also tackled
    the challenge of detecting and classifying objects in high-resolution satellite
    images, achieving competitive results in resource-constrained environments.


    My research extends to self-supervised learning frameworks for temporal segmentation
    in long videos, where I draw inspiration from cognitive psychology to create robust
    representations without the need for extensive labeled data. I have developed
    an ensemble approach, Hydra, for geospatial land classification, which optimizes
    training time while maintaining high performance.


    Additionally, I have explored the intersection of deep learning and biometric
    recognition, particularly in gait analysis, where I introduced a Linear Dynamical
    Systems module to enhance temporal consistency. My work on action recognition
    has led to frameworks that leverage self-supervised learning to effectively localize
    actions in videos, achieving results comparable to fully supervised methods.


    I am passionate about applying my expertise to real-world challenges, such as
    analyzing the economic impacts of the COVID-19 pandemic through satellite imagery.
    My contributions to the field have been recognized in various competitions, and
    I am committed to advancing the state of the art in computer vision through innovative
    methodologies and collaborative research.'
  type: BaseAgent
coordinate_mode: graph
engine_planner:
  initial_progress: Starting the collaborative research idea generation based on the
    provided Introduction.
environment:
  max_iterations: 5
  name: Research Collaboration Environment
  type: Research
llm: together_ai/meta-llama/Llama-3.3-70B-Instruct-Turbo
memory:
  type: SharedMemory
metrics:
  diversity_of_perspectives: true
  engagement_level: true
  evaluate_llm: gpt-4o-mini
  relevance: true
output:
  file_path: result/discussion_output_llama3.3_70b.jsonl
  format: jsonl
relationships:
- - agent1
  - agent2
  - collaborate with
task:
  content: "\n            Dear Research Team,\n\n            You are collaborating\
    \ to generate a new research idea based on the following Introduction:\n\n   \
    \         **Introduction**\n\n               1 Introduction  Modeling the temporal\
    \ associations between consecutive inputs in a sequence (i.e., sequential memory)\
    \ enables biological agents to perform various cognitive functions, such as episodic\
    \ memory formation [45, 55, 14], complex action planning [20] and translating\
    \ between languages [3]. For example, playing a musical instrument requires remembering\
    \ the sequence of notes in a piece of music; similarly, playing a game of chess\
    \ requires simulating, planning, and executing a sequence of moves in a specific\
    \ order. While the ability to form such memories of static, unrelated events has\
    \ been extensively studied [48, 47, 54, 59, 57], the ability of biologically-plausible\
    \ artificial networks to learn and recall temporally-dependent patterns has not\
    \ been sufficiently explored in literature [53]. The task of sequential memory\
    \ is considered challenging for models operating under biological constraints\
    \ (i.e., local synaptic computations) for many reasons, including catastrophic\
    \ forgetting, ambiguous context representations, multiple future possibilities,\
    \ etc.   In addition to the biological constraint, we impose the following set\
    \ of desirable characteristics as learning constraints on sequence memory models.\
    \     •  The learning of one sequence does not overwrite the previously learned\
    \ sequences. This property is defined under the continual learning framework as\
    \ avoiding catastrophic forgetting and evaluated with the Backward Transfer (BWT)\
    \ metric [34].    •  The model should uniquely encode inputs based on their context\
    \ in a sequence. Consider the sequence of letters “EVER”; the representation of\
    \ “E” at position 1 should be different from “E” at position 3, thus resulting\
    \ in different predictions: “V” and “R”. Moreover, the representation of “E” at\
    \ position 3 in “EVER” should be different from “E” at position 3 in “CLEVER”.\
    \ Therefore, positional encoding is not a valid solution.    •  When presented\
    \ with multiple valid, future possibilities, the model should learn to represent\
    \ each possibility separately yet stochastically sample a single valid possibility.\
    \ Consider the two sequences “THAT” and “THEY”; after seeing “TH”, the model should\
    \ learn to generate either “A” or “E”, but not an average [33] or a union of both [23].\
    \    •  The model should be capable of incrementally learning each transition\
    \ without seeing the whole sequence or revisiting older sequence transitions that\
    \ are previously learned. This property falls under online learning constraints,\
    \ also called stream learning [40, 23].    •  The learning algorithm should be\
    \ tolerant and robust to significant input noise. A model should continuously\
    \ clean the noisy inputs using learned priors and beliefs, thus performing future\
    \ predictions based on the noise-free observations [23].      We propose Predictive\
    \ Attractor Models (PAM), which consists of a state prediction model and a generative\
    \ attractor model. The predictor in PAM is inspired by the Hierarchical Temporal\
    \ Memory (HTM) [23] learning algorithm, where a group of neurons in the same cortical\
    \ minicolumn share the same receptive feedforward connection from the sensory\
    \ input on their proximal dendrites. The depolarization of the voltage of any\
    \ neuron in a single minicolumn (i.e., on distal dendrites) primes this depolarized\
    \ neuron to fire first while inhibiting all the other neurons in the same minicolumn\
    \ from firing (i.e., competitive learning). The choice of which neurons fire within\
    \ the same minicolumn is based on the previously active neurons and their trainable\
    \ synaptic weights to the depolarized neurons, which gives rise to a unique context\
    \ representation for every input.\n\n            **Your Task**\n\n           \
    \ 1. **Literature Review**: Analyze the Introduction provided and conduct a brief\
    \ literature review to understand the current state of research in this area.\n\
    \n            2. **Brainstorming**: Collaboratively brainstorm potential research\
    \ ideas that build upon or address gaps in the Introduction.\n\n            3.\
    \ **Summarization**: Summarize your collective ideas.\n\n            4. **Formulate\
    \ a New Research Idea**: Develop a new research proposal in the format of the\
    \ '5q', defined below:\n\n               **Here is a high-level summarized insight\
    \ of a research field Machine Learning.**\n\n               **Here are the five\
    \ core questions:**\n\n               **[Question 1] - What is the problem?**\n\
    \n               Formulate the specific research question you aim to address.\
    \ Only output one question and do not include any more information.\n\n      \
    \         **[Question 2] - Why is it interesting and important?**\n\n        \
    \       Explain the broader implications of solving this problem for the research\
    \ community.\n               Discuss how such a paper will affect future research.\n\
    \               Discuss how addressing this question could advance knowledge or\
    \ lead to practical applications.\n\n               **[Question 3] - Why is it\
    \ hard?**\n\n               Discuss the challenges and complexities involved in\
    \ solving this problem.\n               Explain why naive or straightforward approaches\
    \ may fail.\n               Identify any technical, theoretical, or practical\
    \ obstacles that need to be overcome. MAKE IT CLEAR.\n\n               **[Question\
    \ 4] - Why hasn't it been solved before?**\n\n               Identify gaps or\
    \ limitations in previous research or existing solutions.\n               Discuss\
    \ any barriers that have prevented this problem from being solved until now.\n\
    \               Explain how your approach differs from or improves upon prior\
    \ work. MAKE IT CLEAR.\n\n               **[Question 5] - What are the key components\
    \ of my approach and results?**\n\n               Outline your proposed methodology\
    \ in detail, including the method, dataset, and metrics that you plan to use.\n\
    \               Describe the expected outcomes. MAKE IT CLEAR.\n\n           \
    \ Please work together to produce the '5q' for your proposed research idea.\n\n\
    \            Good luck!\n            "
  output_format: "You should answer the task in the following format:\n          \
    \      **[Question 1] - What is the problem?**\n\n                Formulate the\
    \ specific research question you aim to address. Only output one question and\
    \ do not include any more information.\n\n                **[Question 2] - Why\
    \ is it interesting and important?**\n\n                Explain the broader implications\
    \ of solving this problem for the research community.\n                Discuss\
    \ how such a paper will affect future research.\n                Discuss how addressing\
    \ this question could advance knowledge or lead to practical applications.\n\n\
    \                **[Question 3] - Why is it hard?**\n\n                Discuss\
    \ the challenges and complexities involved in solving this problem.\n        \
    \        Explain why naive or straightforward approaches may fail.\n         \
    \       Identify any technical, theoretical, or practical obstacles that need\
    \ to be overcome. MAKE IT CLEAR.\n\n                **[Question 4] - Why hasn't\
    \ it been solved before?**\n\n                Identify gaps or limitations in\
    \ previous research or existing solutions.\n                Discuss any barriers\
    \ that have prevented this problem from being solved until now.\n            \
    \    Explain how your approach differs from or improves upon prior work. MAKE\
    \ IT CLEAR.\n\n                **[Question 5] - What are the key components of\
    \ my approach and results?**\n\n                Outline your proposed methodology\
    \ in detail, including the method, dataset, and metrics that you plan to use.\n\
    \                Describe the expected outcomes. MAKE IT CLEAR."
