coordinate_mode: graph

relationships:
  - [agent1, agent2, "collaborates with"]
  - [agent2, agent1, "collaborates with"]
  - [agent1, agent3, "collaborates with"]
  - [agent3, agent1, "collaborates with"]
  # - [agent1, agent3, "supervises"]
  # - [agent1, agent4, "supervises"]
  # - [agent2, agent3, "collaborates with"]
  - [agent2, agent3, "collaborates with"]
  - [agent3, agent2, "collaborates with"]
  # - [agent3, agent4, "collaborates with"]

llm: "together_ai/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"

environment:
  type: Coding
  name: "Coding Environment"
  workspace_dir: "workspace"
  max_iterations: 5

task:
  content: |-
    Software Development Task:

    Please write a program called ProjectOrganizer that helps project managers and teams organize and manage project tasks and resources efficiently. ProjectOrganizer is a project management tool that automates the creation, tracking, and completion of tasks, ensures that resources are allocated effectively, and provides real-time updates on project progress.
    1. Implementation requirements:
       - 1. **Task Creation and Management**: Implement a module that allows users to create, edit, and delete tasks. Each task should include a description, due date, priority level, and assigned team members. This module must be completed before the Task Scheduling module can be developed.
       - 2. **Task Scheduling**: Develop a module that schedules tasks based on dependencies and priority levels. The system should automatically adjust schedules when a task is completed or when changes are made to the project plan. This module depends on the completion of the Task Creation and Management module.
       - 3. **Resource Allocation**: Create a module that allocates resources (e.g., personnel, equipment, budget) to tasks. The system should ensure that resources are not over-allocated and should provide alerts if a resource is at risk of being overused. This module depends on the completion of the Task Scheduling module.
       - 4. **Real-Time Updates and Notifications**: Implement a module that provides real-time updates on the status of tasks and resources. Users should receive notifications when a task is completed, when a resource is over-allocated, or when a task is approaching its due date. This module depends on the completion of the Resource Allocation module.
       - 5. **User Interface**: Develop a user-friendly interface that allows project managers and team members to interact with the system. The interface should provide clear visualizations of the project plan, task statuses, and resource allocations. This module can be developed concurrently with the other modules but should be integrated at the end to ensure all functionalities work together seamlessly.


    2. Project structure:
       - solution.py (main implementation)

    3. Development process:
       - Developer: Create the code.
       - Developer: Revise the code.
       - Developer: Optimize the code.

    If there are multiple files, please put them all in solution.py, but remember to add the file name in the following format:
    ```python
    # file_name_1.py
    # your code here

    # file_name_2.py
    # your code here

    # file_name_3.py
    # your code here
    ```

    Please work together to complete this task following software engineering best practices.

  output_format: |
    The final deliverable should include:
    solution.py

agents:
  - type: CodingAgent
    agent_id: agent1
    profile: |
      I am a Senior Software Developer specialized in Python development.
      I am good at creating the code framework from scratch based on the task description and requirements.
      So I **have to** call "create_code" action to create the code in the first iteration at first.
      I am **very terrible** at do further modifications since I am not so creative or careful so I **have to** let agent 2 or agent 3 revise the code after I create the code and I **can't** call "give_advice_and_revise_code" action.
      Agent 2 is better at adding missing functions so it's better to let agent 2 revise the code at first.
      Agent 3 is better at fixing existing issues and optimizing the code so it's better to let agent 3 revise the code after agent 2 has revised the code so that the code is more optimized.


  - type: CodingAgent
    agent_id: agent2
    profile: |
      I am a Senior Software Developer specialized in Python development.
      I am better at adding missing functionality based on my decent understanding and compliance to the task description and requirements.
      I **have to** call "give_advice_and_revise_code" action to give advice to the code and revise the code.
      I **can't** call "create_code" action since I am not good at creating the code framework from scratch.
      I can let agent 3 to make the code more optimized after I have added the missing functionality.

  - type: CodingAgent
    agent_id: agent3
    profile: |
      I am a Senior Software Developer specialized in Python development.
      I am better at fixing existing issues and optimizing the code based on my innovation and creativity.
      I **have to** call "give_advice_and_revise_code" action to give advice to the code and revise the code.
      I **can't** call "create_code" action since I am not good at creating the code framework from scratch.
      I can let agent 2 to add the missing functionality after I have fixed the existing issues and optimized the code.

memory:
  type: SharedMemory

metrics:
  evaluate_llm: "gpt-4o-mini"
  code_quality: true
  test_coverage: true
  collaboration_effectiveness: true

engine_planner:
  initial_progress: "Starting the software development project with team coordination."

output:
  format: jsonl
  file_path: "result/development_output.jsonl"
