coordinate_mode: graph

relationships:
  - [agent1, agent2, "collaborates with"]
  - [agent2, agent1, "collaborates with"]
  - [agent1, agent3, "collaborates with"]
  - [agent3, agent1, "collaborates with"]
  # - [agent1, agent3, "supervises"]
  # - [agent1, agent4, "supervises"]
  # - [agent2, agent3, "collaborates with"]
  - [agent2, agent3, "collaborates with"]
  - [agent3, agent2, "collaborates with"]
  # - [agent3, agent4, "collaborates with"]

llm: "together_ai/meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo"

environment:
  type: Coding
  name: "Coding Environment"
  workspace_dir: "workspace"
  max_iterations: 5

task:
  content: |-
    Software Development Task:

    Please write a program called 'Event_Organizer_Collaborative' that allows multiple agents to collaboratively manage and optimize the planning and execution of various events. Event Organizer Collaborative is a management game software that enables players to work together to handle event logistics, scheduling, budgeting, and guest management. Players can assign tasks, set deadlines, communicate with each other, and adjust plans based on real-time feedback and changing conditions to ensure the success of each event.
    1. Implementation requirements:
       - The system should allow multiple agents to log in and collaborate on event planning, with each agent having distinct roles and responsibilities.
       - Agents should be able to create and manage event details, including location, date, time, and guest list. The system should provide real-time updates and notifications to all agents when changes are made.
       - The system should include a task management feature where agents can assign tasks to each other, set deadlines, and track progress. Tasks should be dynamically adjustable based on user feedback and changing conditions.
       - The system should provide a communication platform for agents to discuss and coordinate their efforts, including features like chat, comments, and file sharing.
       - The system should support budget management, allowing agents to track expenses, set budgets, and receive alerts when costs exceed budget limits. Budgets should be adaptable based on user input and real-time data.
       - The system should offer a dashboard that provides an overview of all ongoing events, including key metrics such as completion status, budget adherence, and guest satisfaction. The dashboard should update in real-time and allow agents to drill down into specific details.
       - The system should be able to adapt to user feedback and changing conditions, such as last-minute cancellations, venue changes, or unexpected expenses, by allowing agents to make quick adjustments to event plans.


    2. Project structure:
       - solution.py (main implementation)

    3. Development process:
       - Developer: Create the code.
       - Developer: Revise the code.
       - Developer: Optimize the code.

    If there are multiple files, please put them all in solution.py, but remember to add the file name in the following format:
    ```python
    # file_name_1.py
    # your code here

    # file_name_2.py
    # your code here

    # file_name_3.py
    # your code here
    ```

    Please work together to complete this task following software engineering best practices.

  output_format: |
    The final deliverable should include:
    solution.py

agents:
  - type: CodingAgent
    agent_id: agent1
    profile: |
      I am a Senior Software Developer specialized in Python development.
      I am good at creating the code framework from scratch based on the task description and requirements.
      So I **have to** call "create_code" action to create the code in the first iteration at first.
      I am **very terrible** at do further modifications since I am not so creative or careful so I **have to** let agent 2 or agent 3 revise the code after I create the code and I **can't** call "give_advice_and_revise_code" action.
      Agent 2 is better at adding missing functions so it's better to let agent 2 revise the code at first.
      Agent 3 is better at fixing existing issues and optimizing the code so it's better to let agent 3 revise the code after agent 2 has revised the code so that the code is more optimized.


  - type: CodingAgent
    agent_id: agent2
    profile: |
      I am a Senior Software Developer specialized in Python development.
      I am better at adding missing functionality based on my decent understanding and compliance to the task description and requirements.
      I **have to** call "give_advice_and_revise_code" action to give advice to the code and revise the code.
      I **can't** call "create_code" action since I am not good at creating the code framework from scratch.
      I can let agent 3 to make the code more optimized after I have added the missing functionality.

  - type: CodingAgent
    agent_id: agent3
    profile: |
      I am a Senior Software Developer specialized in Python development.
      I am better at fixing existing issues and optimizing the code based on my innovation and creativity.
      I **have to** call "give_advice_and_revise_code" action to give advice to the code and revise the code.
      I **can't** call "create_code" action since I am not good at creating the code framework from scratch.
      I can let agent 2 to add the missing functionality after I have fixed the existing issues and optimized the code.

memory:
  type: SharedMemory

metrics:
  evaluate_llm: "gpt-4o-mini"
  code_quality: true
  test_coverage: true
  collaboration_effectiveness: true

engine_planner:
  initial_progress: "Starting the software development project with team coordination."

output:
  format: jsonl
  file_path: "result/development_output.jsonl"
