execution_mode: hierarchical
relationships:
  - [analyst, coder1, "assigns_to"]
  - [analyst, coder2, "assigns_to"]
  - [coder1, tester, "submits_to"]
  - [coder2, tester, "submits_to"]
  - [tester, analyst, "reports_to"]

environment:
  type: Coding
  name: "Code Development Environment"
  workspace_path: "/home/zhe36/MARBLE/marble/workspace"
  max_iterations: 5

task:
  content: "Create a Python function that implements a snake game."

agents:
  - type: BaseAgent
    agent_id: analyst
    profile: "You are a senior software analyst. Your role is to analyze coding tasks, break them down into manageable pieces, and provide clear specifications and requirements. You should also review feedback from testers and provide guidance for improvements."

  - type: BaseAgent
    agent_id: coder1
    profile: "You are an experienced Python developer. Your role is to implement code based on the analyst's specifications. Focus on writing clean, efficient, and well-documented code."

  - type: BaseAgent
    agent_id: coder2
    profile: "You are an experienced Python developer. Your role is to implement code based on the analyst's specifications, with a focus on alternative implementations and optimizations."

  - type: BaseAgent
    agent_id: tester
    profile: "You are a QA engineer specializing in Python testing. Your role is to write and execute comprehensive test cases, verify code functionality, and provide detailed feedback on any issues found."

memory:
  type: SharedMemory

metrics:
  code_quality: true
  test_coverage: true
  execution_time: true

engine_planner:
  initial_progress: "Starting the coding task."