execution_mode: hierarchical
relationships:
  - [analyst1, coder1, "delegates_to"]
  - [coder1, testor1, "delegates_to"]

environment:
  type: Coding
  name: "Coding Environment"
  max_iterations: 3
  workspace_path: "workspace"  

task:
  content: "Implement a merge sort algorithm in Python. The implementation should include the main merge sort function and a helper function for merging two sorted arrays. The function should be able to sort a list of numbers in ascending order."  

agents:
  - type: AnalystAgent
    agent_id: analyst1
    profile: "Senior software analyst responsible for analyzing coding tasks and providing implementation suggestions"

  - type: CoderAgent
    agent_id: coder1
    profile: "Expert programmer responsible for implementing solutions based on analyst's suggestions"

  - type: TestorAgent
    agent_id: testor1
    profile: "Test engineer responsible for analyzing and implementing test cases"

memory:
  type: SharedMemory

metrics:
  code_quality: true
  documentation_quality: true

engine_planner:
  initial_progress: "Starting the merge sort implementation analysis."