execution_mode: hierarchical
relationships:
  - [analyst1, coder1, "delegates_to"]

environment:
  type: Coding
  name: "Coding Environment"
  max_iterations: 2
  workspace_path: "/home/zhe36/MARBLE/marble/workspace"

task:
  content: "Implement a Red-Black Tree data structure in Python with the following operations: insert, delete, search, and traversal methods. The implementation should maintain all Red-Black Tree properties and handle recoloring and rotations appropriately."

agents:
  - type: AnalystAgent
    agent_id: analyst1
    profile: "Senior software analyst responsible for analyzing coding tasks and providing implementation suggestions"

  - type: CoderAgent
    agent_id: coder1
    profile: "Expert programmer responsible for implementing solutions based on analyst's suggestions"

memory:
  type: SharedMemory

metrics:
  code_quality: true
  documentation_quality: true

engine_planner:
  initial_progress: "Starting the Red-Black Tree implementation analysis."