coordinate_mode: star
relationships: []

environment:
  type: DB 
  name: "DB Simulation Environment"
  max_iterations: 5
  # Add other environment-specific configurations here

task:
  content: "Analyze the database alerts & outputs and find out the reason that caused it. The reasons could be: ['INSERT_LARGE_DATA', 'MISSING_INDEXES','LOCK_CONTENTION','VACUUM','REDUNDANT_INDEX','INSERT_LARGE_DATA,IO_CONTENTION', 'FETCH_LARGE_DATA,CORRELATED_SUBQUERY','POOR_JOIN_PERFORMANCE,CPU_CONTENTION']. Only one of these reasons would apply. The planner should ask different experts to work on same task, and summarize their opinions into a final prediction."

agents:
  - type: BaseAgent
    agent_id: ConfigurationExpert
    profile: "ConfigurationExpert specializes in system configurations and optimizations."
  - type: BaseAgent
    agent_id: CpuExpert
    profile: "CpuExpert is knowledgeable in CPU architecture, performance, and optimizations."
  - type: BaseAgent
    agent_id: DiskExpert
    profile: "DiskExpert has expertise in storage systems, disk management, and performance tuning."
  - type: BaseAgent
    agent_id: IndexExpert
    profile: "IndexExpert is skilled in indexing techniques, data retrieval, and optimization strategies."
  - type: BaseAgent
    agent_id: IoExpert
    profile: "IoExpert focuses on input/output systems, data flow, and optimizing throughput."
  - type: BaseAgent
    agent_id: MemoryExpert
    profile: "MemoryExpert is an expert in memory management, optimization, and troubleshooting."
  - type: BaseAgent
    agent_id: QueryExpert
    profile: "QueryExpert specializes in query optimization, execution plans, and performance improvement."
  - type: BaseAgent
    agent_id: RecoveryExpert
    profile: "RecoveryExpert is proficient in data recovery, fault tolerance, and system restoration techniques."
  - type: BaseAgent
    agent_id: WorkloadExpert
    profile: "WorkloadExpert excels in analyzing workloads, resource allocation, and optimization for efficiency."

memory:
  type: SharedMemory
  # Additional memory configurations if needed

metrics:
  # Define metrics configurations for the Evaluator
  # Example:
  # accuracy: true
  # response_time: true

engine_planner:
  initial_progress: "Starting the simulation."
  # Additional engine planner configurations if needed
