execution_mode: hierarchical
relationships:
  - [agent1, agent2, "reports_to"]
  - [agent1, agent3, "manages"]
  - [agent2, agent4, "supports"]
  - [agent3, agent4, "collaborates_with"]

environment:
  type: Web
  name: "Web Simulation Environment"
  max_iterations: 1
  # Add other environment-specific configurations here

task:
  content: "Find new about the latest trends in AI and have agent1 to summarize it in the end."

agents:
  - type: BaseAgent
    agent_id: agent1
    profile: "agent1 is a helpful and supportive team leader. agent1 will use bing to search results for the task."
    # Additional agent-specific configurations
  - type: BaseAgent
    agent_id: agent2
    profile: "agent2 is a curious and ambitious team member. agent1 will use google to search results for the task."
    # Additional agent-specific configurations
  - type: BaseAgent
    agent_id: agent3
    profile: "agent3 are a diligent and hardworking team member. agent3 will use wikipedia to search results for the task."
    # Additional agent-specific configurations
  - type: BaseAgent
    agent_id: agent4
    profile: "agent4 is a creative and innovative team member. agent4 will use twitter to search results for the task."
    # Additional agent-specific configurations

memory:
  type: SharedMemory
  # Additional memory configurations if needed

metrics:
  # Define metrics configurations for the Evaluator
  # Example:
  # accuracy: true
  # response_time: true

engine_planner:
  initial_progress: "Starting the simulation."
  # Additional engine planner configurations if needed
