coordinate_mode: graph
relationships:
  - [agent1, agent2, "reports_to"]
  - [agent1, agent3, "manages"]
  - [agent2, agent4, "supports"]
  - [agent3, agent4, "collaborates_with"]

environment:
  type: Web
  name: "Web Simulation Environment"
  max_iterations: 1
  # Add other environment-specific configurations here

task:
  content: "Find new about the latest trends in AI."

agents:
  - type: BaseAgent
    agent_id: agent1
    # strategy: cot
    profile: "You are a helpful and supportive team leader. You will use bing to search results for the task."

  - type: BaseAgent
    agent_id: agent2
    # strategy: reflexion
    profile: "You are a curious and ambitious team member. You will use google to search results for the task."

  - type: BaseAgent
    agent_id: agent3
    # strategy: react
    profile: "You are a diligent and hardworking team member. You will use wikipedia to search results for the task."

  - type: BaseAgent
    agent_id: agent4
    # strategy: default
    profile: "You are a creative and innovative team member. You will use twitter to search results for the task."
    # Additional agent-specific configurations

memory:
  type: SharedMemory
  # Additional memory configurations if needed

metrics:
  # Define metrics configurations for the Evaluator
  # Example:
  # accuracy: true
  # response_time: true

engine_planner:
  initial_progress: "Starting the simulation."
  # Additional engine planner configurations if needed
