execution_mode: hierarchical
relationships:
  - [agent1, agent2, "reports_to"]
  - [agent1, agent3, "manages"]
  - [agent2, agent4, "supports"]
  - [agent3, agent4, "collaborates_with"]

environment:
  type: Web
  name: "Web Simulation Environment"
  max_iterations: 20
  # Add other environment-specific configurations here

agents:
  - type: BaseAgent
    agent_id: agent1
    # Additional agent-specific configurations
  - type: BaseAgent
    agent_id: agent2
    # Additional agent-specific configurations
  - type: ReasoningAgent
    agent_id: agent3
    # Additional agent-specific configurations
  - type: BaseAgent
    agent_id: agent4
    # Additional agent-specific configurations

memory:
  type: SharedMemory
  # Additional memory configurations if needed

metrics:
  # Define metrics configurations for the Evaluator
  # Example:
  # accuracy: true
  # response_time: true

engine_planner:
  initial_progress: "Starting the simulation."
  # Additional engine planner configurations if needed
