coordinate_mode: graph
relationships:
  - [agent1, agent2, "collaborate with"]
  - [agent1, agent3, "collaborate with"]
  - [agent2, agent3, "collaborate with"]

environment:
  type: Minecraft
  name: "Minecraft Environment"
  host: "localhost"
  port: 25565
  max_iterations: 10
  task_id: 6
  task_name: test
  # Add other environment-specific configurations here

task:
  content: "This is in the game of Minecraft. Build a building according to the following description: smooth_sandstone facing direction A at position [-9, -60, 0], smooth_sandstone facing direction A at position [-10, -60, 0], smooth_sandstone facing direction A at position [-9, -60, 1], smooth_sandstone facing direction A at position [-10, -60, 1], smooth_sandstone facing direction A at position [-10, -60, -1], smooth_sandstone facing direction A at position [-8, -60, 0]. Hint: useful materials are in a chest. withdraw the materials and place them in the correct position and correct orientation. if you cannot reach a desired place, use a ladder."

agents:
  - type: BaseAgent
    agent_id: agent1
    agent_port: 5000
    profile: "agent1 is a pragmatic team member. agen1 prefers doing more actual work rather than talking."
    # Additional agent-specific configurations
  - type: BaseAgent
    agent_id: agent2
    agent_port: 5001
    profile: "agent2 is a talkative team member. agent2 talks more than doing actual work."
    # Additional agent-specific configurations
  - type: BaseAgent
    agent_id: agent3
    agent_port: 5002
    profile: "agent3 is a deliberate team member. agent3 likes making reflections and giving guidance to team members."
    # Additional agent-specific configurations

memory:
  type: SharedMemory
  # Additional memory configurations if needed

metrics:
  # Define metrics configurations for the Evaluator
  # Example:
  evaluate_llm:
    model: gpt-3.5-turbo
    provider: openai

engine_planner:
  initial_progress: "Starting the simulation."
  # Additional engine planner configurations if needed

llm: gpt-3.5-turbo

output:
  file_path: result/minecraft/discussion_output_gpt_35_turbo.jsonl